local emphasis = require('gutenberg.api.emphasis')

local with_buffer = require('gutenberg.tests.utils').with_buffer

describe('gutenberg.api.emphasis', function()
  describe('is_emphasis', function()
    it('returns true inside a `*` emphasis', function()
      with_buffer({ 'a *em* b' }, { 1, 4 }, function(ctx)
        assert.is_true(emphasis.is_emphasis(ctx))
      end)
    end)

    it('returns true inside a `_` emphasis', function()
      with_buffer({ 'a _em_ b' }, { 1, 4 }, function(ctx)
        assert.is_true(emphasis.is_emphasis(ctx))
      end)
    end)

    it('returns false on plain text', function()
      with_buffer({ 'plain text' }, { 1, 3 }, function(ctx)
        assert.is_false(emphasis.is_emphasis(ctx))
      end)
    end)

    it('returns false on strong emphasis', function()
      with_buffer({ 'a **bold** b' }, { 1, 5 }, function(ctx)
        assert.is_false(emphasis.is_emphasis(ctx))
      end)
    end)
  end)

  describe('read', function()
    it('strips the `*` delimiters', function()
      with_buffer({ 'a *em* b' }, { 1, 4 }, function(ctx)
        assert.equal('em', emphasis.read(ctx).text)
      end)
    end)

    it('strips the `_` delimiters', function()
      with_buffer({ 'a _em_ b' }, { 1, 4 }, function(ctx)
        assert.equal('em', emphasis.read(ctx).text)
      end)
    end)

    it('reads emphasis wrapping strong in ***both***', function()
      with_buffer({ 'a ***both*** b' }, { 1, 6 }, function(ctx)
        assert.equal('**both**', emphasis.read(ctx).text)
      end)
    end)

    it('reads the inner span of nested emphasis', function()
      with_buffer({ 'a *o *i* c* b' }, { 1, 6 }, function(ctx)
        assert.equal('i', emphasis.read(ctx).text)
      end)
    end)

    it('returns a TSNode spanning the whole span', function()
      with_buffer({ 'a *em* b' }, { 1, 4 }, function(ctx)
        local _, node = emphasis.read(ctx)
        local _, sc, _, ec = node:range()
        assert.equal(2, sc)
        assert.equal(6, ec)
      end)
    end)

    it('errors off a span', function()
      with_buffer({ 'plain' }, { 1, 0 }, function(ctx)
        assert.error_matches(function()
          emphasis.read(ctx)
        end, 'cursor is not on emphasis')
      end)
    end)
  end)

  describe('render', function()
    it('emits the configured delimiter, default `_`', function()
      assert.equal('_x_', emphasis.render({ text = 'x' }))
    end)

    it('honors a `*` override from setup', function()
      require('gutenberg.config').merge({ emphasis = { delimiter = '*' } })
      local ok, err = pcall(function()
        assert.equal('*x*', emphasis.render({ text = 'x' }))
      end)
      require('gutenberg.config').merge()
      if not ok then
        error(err)
      end
    end)

    it('re-emits inner strong in the configured delimiter', function()
      with_buffer({ 'a ***both*** b' }, { 1, 6 }, function(ctx)
        assert.equal('_**both**_', emphasis.render(emphasis.read(ctx)))
      end)
    end)
  end)

  describe('replace', function()
    it('rewrites the span in place', function()
      with_buffer({ 'a *em* b' }, { 1, 4 }, function(ctx)
        local value, node = emphasis.read(ctx)
        emphasis.set_text(value, 'new')
        emphasis.replace(node, { value }, ctx)
        assert.same(
          { 'a _new_ b' },
          vim.api.nvim_buf_get_lines(ctx.bufnr, 0, -1, false)
        )
      end)
    end)

    it('deletes the span for an empty list', function()
      with_buffer({ 'a *em* b' }, { 1, 4 }, function(ctx)
        local _, node = emphasis.read(ctx)
        emphasis.replace(node, {}, ctx)
        assert.same(
          { 'a  b' },
          vim.api.nvim_buf_get_lines(ctx.bufnr, 0, -1, false)
        )
      end)
    end)
  end)

  describe('accessors', function()
    it('get/set text round-trips', function()
      local value = emphasis.create({ text = 'a' })
      assert.equal('a', emphasis.get_text(value))
      emphasis.set_text(value, 'b')
      assert.equal('b', emphasis.get_text(value))
    end)
  end)
end)
