local strong = require('gutenberg.api.strong')

local with_buffer = require('gutenberg.tests.utils').with_buffer

describe('gutenberg.api.strong', function()
  describe('is_strong', function()
    it('returns true inside `**` strong', function()
      with_buffer({ 'a **bold** b' }, { 1, 5 }, function(ctx)
        assert.is_true(strong.is_strong(ctx))
      end)
    end)

    it('returns true inside `__` strong', function()
      with_buffer({ 'a __bold__ b' }, { 1, 5 }, function(ctx)
        assert.is_true(strong.is_strong(ctx))
      end)
    end)

    it('returns false on plain emphasis', function()
      with_buffer({ 'a *em* b' }, { 1, 4 }, function(ctx)
        assert.is_false(strong.is_strong(ctx))
      end)
    end)
  end)

  describe('read', function()
    it('strips the `**` delimiters', function()
      with_buffer({ 'a **bold** b' }, { 1, 5 }, function(ctx)
        assert.equal('bold', strong.read(ctx).text)
      end)
    end)

    it('strips the `__` delimiters', function()
      with_buffer({ 'a __bold__ b' }, { 1, 5 }, function(ctx)
        assert.equal('bold', strong.read(ctx).text)
      end)
    end)

    it('reads strong nested inside emphasis (***both***)', function()
      with_buffer({ 'a ***both*** b' }, { 1, 6 }, function(ctx)
        local value, node = strong.read(ctx)
        assert.equal('both', value.text)
        assert.equal('strong_emphasis', node:type())
      end)
    end)

    it('errors off a span', function()
      with_buffer({ 'plain' }, { 1, 0 }, function(ctx)
        assert.error_matches(function()
          strong.read(ctx)
        end, 'cursor is not on strong emphasis')
      end)
    end)
  end)

  describe('render', function()
    it('emits the configured delimiter, default `**`', function()
      assert.equal('**x**', strong.render({ text = 'x' }))
    end)

    it('honors a `__` override from setup', function()
      require('gutenberg.config').merge({ strong = { delimiter = '__' } })
      local ok, err = pcall(function()
        assert.equal('__x__', strong.render({ text = 'x' }))
      end)
      require('gutenberg.config').merge()
      if not ok then
        error(err)
      end
    end)

    it('round-trips `__bold__` to `**bold**`', function()
      with_buffer({ 'a __bold__ b' }, { 1, 5 }, function(ctx)
        assert.equal('**bold**', strong.render(strong.read(ctx)))
      end)
    end)
  end)

  describe('replace', function()
    it('rewrites the span in place', function()
      with_buffer({ 'a **bold** b' }, { 1, 5 }, function(ctx)
        local value, node = strong.read(ctx)
        strong.set_text(value, 'new')
        strong.replace(node, { value }, ctx)
        assert.same(
          { 'a **new** b' },
          vim.api.nvim_buf_get_lines(ctx.bufnr, 0, -1, false)
        )
      end)
    end)
  end)
end)
